name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_PERSONAL_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_USERNAME }}
          password: ${{ secrets.CI_PERSONAL_TOKEN }}

      - name: Build and push to Docker registries
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/helo-system/heloserver:latest

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.DEPLOY_WEBHOOK }}
          webhook_secret: ${{ secrets.DEPLOY_SECRET }}
          silent: true
